language: minimal


env:
  global:
    - secure: DzcmYYEs1fiwubqif111y4RD8ilprDQUOnlepIPHoBuTVr/Wu59itQqOzoQzzLsOQEuQZhBBfJU56jLGipNSp9pBHNaV6qZHqabJ5dyyfTKaO/hvjlTs1wBPEwg1iN0yrVCQ9KxWPUHtSRsrQZ8Spa8Adqn4I1k9VHHLiInWGT8lDehXpm6OygW93sgPo9lUjbbhsLMmkxPdxrGC0/Fdrj7oVtpCjWaF3gBLRJhlauTSTKOI5HL1gUVaJyAALyIx7aWmE96xUMGpaeY7ISXkPRSdfxQTs2qCW6eLoJMzuzay+FFnJ/9adbp4bj5q/Ern75eKmqm2SmKsF0FUISxehVN62wYsoqGUBrXK26+ke3RJoo6iIyu5y5mJ3wcZG/gtdUuf3FmvJuH2UeSukSGAtrT5TvwltNBnjDWSRBGPnRxSANUwPmjsk9d0/Qrput2BXKd1z1TUaYQW0VnbY61TxqM/iTXB33tOCpu1qUfxrf8K9I+AJsOiZtz4DDOTOXpacT6roalWHe+QubGUtLOOfjn+Ak2haZkv4saFHyiNxnUD0yisqhw2MSjiaCop4XTvNgLnEiR+8YVG76JZkvsQtnHf9O0bJJv/1q9ijUTDAyj+qk/EHQslkKDiEPrgZpIZQKhY1IoOQZeTdWJ48p3WDkELsX3drrtSCBUhyd3t7So=
    - secure: ANnEftRmmSPqg2AJvil8tkFhJIFulMlza5KkQE9AXcLwzCD+cjt8qyJXC/gGJg+hZfjT7ep3h8uVU8QWq+xh561dA4FXhkr9dazwecwunwbneYYMDqxHLfw1NTgFbM/HxxFCGwaVTwlMsdY95jS/0dQ+EWkHhGIDlQQ128rYQ9TPUXXwULVMJepdWJR9es7e2x5Rti6ki5uFKi8f0WzVasZZRf3LzqeCd88N8/b1UwX7w8Tz8J/CMKFDxLgku/0Wbd/NTU8FuPk9vQN2wgDd9R0QkgyOHnBe+dl35mJPdtCIfqHjl1KcGHqehpcXvSLgSg1lSdYZi0gpunoD0uwICCIENSyPVyVRHEN5UepoDS3pXweBuV+LaBy4Z6+qusiaTEcycYGqn+NBxhwUh5vVSNE2CFDK4hXxdI3bNZR34nHg2RE5Mn/UC2QjDD3A7Qrip8f/3EmsQtCIRH4Vxzj3Y08tZbqPYwv3DqIXJhQfVphKHLm27NGmf8WGAcviqu3GRyEKqP+7baLxb0xBd+DC1l4KE5++M+3mmb80IkUYSNVCPh3OFFqXccURRcJeoWqhxbb7GI6T0lvSLOT5YpmIIA8bk0mGEUNSVdOkmAuIT+QAjY2F7OuOkcq0PFPdcF2K9g0rE3af7odnM0dDaBGFQruIhd2EW9pzvrbyAkcRKeQ=


install:
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then
    eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)";
  fi


script:
  - swift test


matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode10.1
